### ISSUE TITLE
one problem left... :D

### ISSUE THREAD

**Issue by Cremaxx** [popcorncolonel/TwitchBotDetector#5]
what is this:D?

Traceback (most recent call last):
  File "bdb.py", line 1, in <module>
    from twitch_chatters import search_all_games, remove_offline
  File "C:\Python27\twitch_chatters.py", line 24, in <module>
    import handle_twitter
  File "C:\Python27\handle_twitter.py", line 98
SyntaxError: Non-ASCII character '\xc3' in file C:\Python27\handle_twitter.py on line 98, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

i want that the tool posts tweets

**Comment by Cremaxx** [comment]
#solved
